Rolling back multisite index to upstream
Automattic/ElasticPress pull request #102
Opened 2021-08-12 08:40 UTC by pauarge

## Description

## Checklist

Please make sure the items below have been covered before requesting a review:

- [ ] This change works and has been tested locally (or has an appropriate fallback).
- [ ] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

## Steps to Test

2021-08-12 21:03 UTC, rinatkhaziev commented
@pauarge  thank you for jumping on this! 

However, I don't think I agree with rolling back the network-wide lock is the correct approach. We've switched to per-site on purpose because we had an issue with large multisites taking forever to get indexed. I.e. with per-site locks, we were able to index several sites at the same time (I think the max we tried is twelve at once), so it's a great time-saver.

2021-08-13 10:12 UTC, pauarge commented
@rinatkhaziev I see your point. In that case, does it make sense to change the parts of the code that check a for a network-wide lock and do the site-only everywhere?

2021-08-13 16:48 UTC, rinatkhaziev commented
@pauarge I think so, and also add the comments to those places so that it won't get overwritten by accident on the next merge.

2021-08-16 15:49 UTC, rinatkhaziev requested changes
@pauarge thank you! left a bit of feedback but mostly it pertains to the fact we need to add comments to avoid a similar situation in the future.

2021-08-16 15:49 UTC, rinatkhaziev commented on includes/dashboard.php
> +		$wpcli_sync           = (bool) get_transient( 'ep_wpcli_sync' );
I think this whitespace change should be this
```suggestion
		$wpcli_sync = (bool) get_transient( 'ep_wpcli_sync' );
```

2021-08-16 15:49 UTC, rinatkhaziev commented on includes/classes/Command.php
Let's annotate here that this is a "hack" and differs from upstream on purpose, so that the next time we merge this won't get overwritten again.

2021-08-16 15:49 UTC, rinatkhaziev commented on includes/classes/Command.php
> +		set_transient( 'ep_wpcli_sync', true, $this->transient_expiration );
Let's annotate here that this is a "hack" and differs from upstream on purpose, so that the next time we merge this won't get overwritten again.

2021-08-16 15:49 UTC, rinatkhaziev commented on includes/utils.php
>  function is_indexing() {
Let's annotate here that this is a "hack" and differs from upstream on purpose, so that the next time we merge this won't get overwritten again.

2021-08-16 15:59 UTC, rinatkhaziev commented
Additionally, a test is failing now, but I'm not sure what would be the best way forward 

```
1) ElasticPressTest\TestUtils::testIsIndexing
Failed asserting that true is false.
```

2021-08-17 15:11 UTC, pauarge commented
@rinatkhaziev I have managed to make the unit tests pass. However, the Acceptance ones still fail. They are a bit tricky to run, since they take roughly an hour in CI and something of that order of magnitude locally.

2021-08-25 01:25 UTC, rinatkhaziev approved these changes
Thank you and sorry for the delay. 

I honestly thought we deployed this 😬

2021-08-27 18:36 UTC, merged