fixes the array flattening option
Automattic/ElasticPress pull request #87
Opened 2021-05-14 04:38 UTC by ovidiul

## Description
This PR fixes an issue with displaying the aggregated filters widget by properly flattening an array tree.

## Checklist

Please make sure the items below have been covered before requesting a review:

- [x] This change works and has been tested locally (or has an appropriate fallback).
- [x] This change works and has been tested on a Go sandbox.
- [ ] This change has relevant unit tests (if applicable).
- [ ] This change has relevant documentation additions / updates (if applicable).

2021-06-02 07:52 UTC, pschoffer requested changes

2021-06-02 07:52 UTC, pschoffer commented on includes/utils.php
> +}
Fixing indentation 

```suggestion
function flatten_tree_array( $arr ) {
	$result = [];
	foreach ( $arr as $item ) {
		if ( isset( $item->children ) ) {
			$result = array_merge( $result, flatten_tree_array( $item->children ) );
		}
		unset( $item->children );
		$result[] = $item;  
	}
	return $result;
}
```

2021-06-02 09:04 UTC, ovidiul commented on includes/utils.php
> +}
Indentation fixed now

2021-06-02 09:06 UTC, ovidiul commented
Hi @pschoffer indentation is fixed now, I have also moved the tests from #88 PR here and refactored them to include the suggested data provider, thanks for the suggestion.

2021-06-02 12:44 UTC, pschoffer requested changes

2021-06-02 12:44 UTC, pschoffer commented on includes/utils.php
>  		return $flat_tree;
Please replace with the upstream fix:
https://github.com/10up/ElasticPress/commit/cd4183708c63f45a064220eb4b19866d1f417f37

So changing `$to_process = $term->children + $to_process;` to `$to_process = array_merge( $term->children, $to_process );`

The reason this was failing for your use case. is that `+` will not merge items with the same index.

2021-06-03 08:51 UTC, pschoffer approved these changes
Perfect, thank you for this!

2021-06-03 08:52 UTC, merged